models/cinema.py
from marshmallow import fields
from marshmallow.validate import Length
from pkg_init import db, ma
class Cinema(db.Model):
    __tablename__='cinemas'
    id=db.Column(db.Integer, primary_key=True)
    cinema_name= db.Column(db.String)
    registed_date = db.Column(db.DateTime(timezone=True), server_default=db.sql.func.now())
    
    movies=db.relationship("Movie", secondary="movie_seat", back_populates="cinemas",cascade="all, delete")
    seats=db.relationship("Seat", secondary="movie_seat",back_populates="cinemas", cascade="all, delete")
    
    admin_id = db.Column(db.Integer, db.ForeignKey("admin.id"), nullable=False)
    

    orders=db.relationship("Order", backref="cinemas", cascade="all, delete")
    sessions = db.relationship("Session", back_populates="cinema")
    
class CinemaSchema(ma.Schema):
    cinema_name=fields.String(validate=Length(min=3))
    
    class Meta:
        fields=("id","cinema_name","movies","admin_id")
    
    movies= fields.List(fields.Nested("MovieSchema",exclude=('votes',"comments","schedules")))
    # orders= fields.List(fields.Nested("OrderSchema",exclude=("cinema_id",)))
    
    

controllers/admin_ctl.py
from datetime import timedelta
import os
from flask import Blueprint, abort, flash, make_response, redirect, render_template, request, jsonify,session, url_for
from pkg_init import db, bcrypt
import jwt
from flask_jwt_extended import create_access_token, get_jwt_identity, jwt_required,create_refresh_token , set_access_cookies, set_refresh_cookies
from models.admin import Admin, AdminSchema
from models.users import User, UserSchema
from models.orders import Order, OrderSchema
from flask_login import login_user,login_required,current_user, logout_user

app_admin=Blueprint("admin",__name__)

# admin login function check
def admin_required():
    user_id = get_jwt_identity()
    stmt = db.select(Admin).filter_by(id=user_id)
    user=db.session.scalar(stmt)
    if not (user and user.admin):
        abort(401)
    else:
        return user
    
# admin login
@app_admin.route("/admin",methods=('GET', 'POST'))
def admin_login():
    # user_token = session.get('user_token')
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user =Admin.query.filter_by(email=username).first()
        # print('user', user, user.email)
        if user is None:
            error = 'Incorrect username.'
        elif not bcrypt.check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            # session.clear()
            expire=timedelta(days=1)
            access_token=create_access_token(identity=user.id,expires_delta=expire)
            refresh_token = create_refresh_token(identity=user.id,expires_delta=expire)
            # session['user_token'] = access_token
            login_user(user, remember=True)
            return redirect(url_for('cinema.get_cinema'))
            # resp = make_response(redirect(url_for('cinema.get_cinema')))
            # resp.set_cookie('resp', access_token)
            # # set_refresh_cookies(resp, refresh_token)
            # return resp

        flash(error)
    return render_template('auth/login.html')
    
    '''
    # retrieve input data
    user_info=AdminSchema().load(request.form)
    user=Admin.query.filter_by(email=user_info['email']).first()
    # error if admin not exist
    if not user :
        return {"error":"user not exist"},404
    # error if password incorrect
    elif not bcrypt.check_password_hash(user.password,user_info['password']):
        return {"error":"Incorrect username and password"}, 402
    # generate token for further use
    expire=timedelta(days=1)
    access_token=create_access_token(identity=user.id,expires_delta=expire)
    # return data for further use
    return {"user":user.username,"id":user.id, "token":access_token}
    
    '''


@app_admin.route('/logout')
@login_required
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('admin.admin_login'))        





# update user info
@app_admin.route("/admin",methods=['PUT'])
@jwt_required()
def update_user():
    # check admin login
    admin=admin_required()
    # get use input
    user_info= AdminSchema().load(request.form)
    # update user information
    admin.username= user_info.get("username", admin.username)
    if user_info.get("password", admin.password) != admin.password:
        admin.password=bcrypt.generate_password_hash(user_info.get("password", admin.password)).decode('utf-8')
    admin.email=user_info.get("email", admin.email)
    db.session.commit()
    return AdminSchema().dump(admin), 201

# retrieve all customers' data 
@app_admin.route("/admin/users",methods=['GET'])
@login_required
def get_users():
    # admin=admin_required()
    users = User.query.all()
    res=UserSchema(many=True,exclude=['password','comments','votes']).dump(users)
    # return jsonify(res)
    return render_template('cinema/all_users.html', users=res,user=current_user.username)

controllers/movie_ctl.py
from controllers.user_ctl import user_login_required
from models.orders import Order
from models.seats import Seat
from models.movie_seat import Movie_Seat,MovieSeatSchema
from models.sessions import Session, SessionSchema
from controllers.seat_ctl import get_all_seats_by_cinema
from flask_jwt_extended import  get_jwt_identity, jwt_required
from controllers.order_ctl import get_order_ss
from controllers.cinema_ctl import get_cinemas
from models.cinema import CinemaSchema
from sqlalchemy import exc, select, text
from flask import Blueprint, flash, json, redirect, render_template, request, url_for
from sqlalchemy import func
from marshmallow.exceptions import ValidationError
from controllers.user_ctl import owner_required
from pkg_init import db
from controllers.admin_ctl import admin_required
from models.movies import MovieSchema, Movie
from models.cinema import Cinema
from models.votes import Vote, VoteSchema
from flask_login import login_user,login_required,current_user, logout_user
from sqlalchemy.sql import exists

app_movie = Blueprint("movie", __name__)


'''
in-use
'''
@app_movie.route("/ajax_movies_bind_seat", methods=['GET'])
def filter_movie_seat():
    stmt=db.select(Movie)
    movie=db.session.scalars(stmt)
    posts =  MovieSchema(many=True).dump(movie)
    return posts

@app_movie.route("/allmovies", methods=('GET', 'POST'))
def all_movies():
    posts = filter_movie_seat()
    if request.method == 'POST':
        movie_name = request.form['movie_name']
        movie_poster = request.form['movie_poster']
        introduction = request.form['introduction']
        new_movie = Movie(
            movie_poster=movie_poster,
            movie_name=movie_name,
            introduction = introduction,
        )
        db.session.add(new_movie)
        db.session.commit()
        return redirect(url_for('movie.all_movies'))
    return render_template('cinema/main.html',posts=posts,user=current_user.username)

'''
suppose to filter the movie not in the select room in selected cinema

SELECT m.*
FROM movies m
LEFT JOIN movie_seat_relation msr ON m.movie_id = msr.movie_id
LEFT JOIN seats s ON msr.seat_id = s.seat_id
WHERE s.seat_id IS NULL;
'''
@app_movie.route("/ajax_movies_bind_seat/<int:a>/<int:b>", methods=['GET'])
def filter_movie_notbind_seat(a,b):
    stmt = text("""
        SELECT(m.movie_name, m.id)
        FROM movies m
        LEFT JOIN movie_seat msr ON m.id = msr.movie_id AND msr.seat_id =:seat_id AND msr.cinema_id=:cinema_id
        WHERE msr.seat_id IS NULL;
        """
    ).params(seat_id=b,cinema_id=a)

    movies = db.session.scalars(stmt).all()
    movies_list = [{"movie_name": movie.split(',')[0].strip("('"), "id": int(movie.split(',')[1].strip("')"))} for movie in movies]
    print("sas",movies)
    return movies_list

@app_movie.route("/ajax_movies_cinema/<int:a>", methods=['GET'])
def get_all_movies_fromcinam(a):
    stmt=db.select(Movie).filter_by(cinema_id=a)
    movie=db.session.scalars(stmt)
    posts =  MovieSchema(many=True).dump(movie)
    return posts

@app_movie.route("/ajax_movies/<int:a>/<int:b>", methods=['GET'])
def get_all_movies(a,b):
    stmt=db.select(Movie_Seat).filter_by(seat_id=a, cinema_id=b)
    movie_id=db.session.scalars(stmt)
    posts =  MovieSeatSchema(many=True).dump(movie_id)
    movies=[]
    for i in posts:
        movie_=Movie.query.filter_by(id=i['movie_id']).first()
        movies_ =  MovieSchema().dump(movie_)
        movies.append(movies_)
    return movies

# retrive all movies data
'''
@app_movie.route("/cinema/<int:id>/movies", methods=('GET', 'POST'))
@login_required
def get_movies(id):
    seats = get_all_seats_by_cinema(id)
    if request.method == 'POST':
        movie_name = request.form['movie_name']
        introduction = request.form['introduction']
        new_movie = Movie(
            movie_name=movie_name,
            introduction = introduction,
        )
        db.session.add(new_movie)
        db.session.commit()
        return redirect(url_for('movie.get_movies',id=id))
    posts = get_cinemas()
    stmt = db.select(Movie)
    movies = db.session.scalars(stmt)
    movie =  MovieSchema(many=True, exclude=['votes','comments']).dump(movies)
    return render_template('cinema/main.html',seats=seats, movies=movie,posts=posts,user=current_user.username)
'''

@app_movie.route("/singlemovie/<int:movie_id>/<int:user_id>", methods=['GET'])
def get_usert_vote_status(movie_id, user_id):
    vote = Vote.query.filter_by(movie_id=movie_id, user_id=user_id).first()
    if vote:
        vote_=VoteSchema().dump(vote)
        return {'vote_id':vote_['id']}
    else: 
        return {'vote_id':""}

# retrieve single movie data
@app_movie.route("/singlemovie/<int:movie_id>", methods=['GET'])
def get_single_movie(movie_id):
    # check if movie exist, error if not
    
    movie=Movie.query.filter_by(id=movie_id).first()
    if not movie:
        return {'error':'movie not exist'}
    # if any user voted, check the votes count: up and down
    if movie.votes:
        stmt = (
                select(Vote.id, func.count(Vote.vote_status))
                .join_from(Movie, Vote)
                .group_by(Vote.vote_status,Movie.id,Vote.id)
                .having(Movie.id==movie.id, Vote.vote_status==True)
                )
        votesup=db.session.scalars(stmt).all()
        stmt_down = (
                select(Vote.id, func.count(Vote.vote_status))
                .join_from(Movie, Vote)
                .group_by(Vote.vote_status,Movie.id, Vote.id)
                .having(Movie.id==movie.id, Vote.vote_status==False)
                )
        votesdown=db.session.scalars(stmt_down).all()
        # return value for using
        return {'movie': MovieSchema().dump(movie), "vote_up":len(votesup), "vote_down":len(votesdown)}
    else:
        return {"movie":MovieSchema(exclude=("schedules",)).dump(movie),"vote_up":None, "vote_down":None}



# update single movie
@app_movie.route("/movies/<int:movie_id>",methods=('GET', 'POST'))
@login_required
def update_movie(movie_id):
    # check admin authorization
    # admin_required()

    # posts = get_cinemas()
    # check if movie exist , error if not
    movie_check=Movie.query.filter_by(id=movie_id).first()
    # get use input
    # movie= MovieSchema().load(request.form)
    if not movie_check:
        return {"error":"movie not found"}
    # update movie name
    if request.method == 'POST':
        movie_name = request.form['movie_name']
        movie_poster=request.form['movie_poster']
        introduction = request.form['introduction']

        movie_check.movie_name=movie_name
        movie_check.movie_poster=movie_poster
        movie_check.introduction=introduction
        db.session.commit()
        return redirect(url_for('movie.all_movies'))
    movie_e= MovieSchema().dump(movie_check)
    return render_template('cinema/update.html', post=movie_e,user=current_user.username)



# delete single movie
@app_movie.route("/movies/delete/<int:movie_id>",methods=('POST',))
@login_required
def delete_movie(movie_id):
    # check admin authorization
    # admin_required()

    # check if movie exist
    movie_select=Movie.query.filter_by(id=movie_id).first()
    print('sel', movie_select)
    # check the session for the movie
    session_check=Session.query.filter_by(movie_id=movie_id).first()
    if session_check:
        session_e= SessionSchema().dump(session_check)
        # check if ordered the movie yet
        order_check=Order.query.filter_by(session_id=session_e['id']).first()
        if order_check:
            error = "movie can't be deleted because already booked to play"
            flash(error)
            return redirect(url_for('movie.all_movies'))

    # delete movie
    db.session.delete(movie_select)
    db.session.commit()
    return redirect(url_for('movie.all_movies'))
    # return "movie deleted"

controllers/seat_ctl.py
from models.movies import Movie
from models.movie_seat import Movie_Seat
from flask_jwt_extended import  jwt_required
from flask import Blueprint, flash, redirect, render_template, request, url_for
from controllers.cinema_ctl import get_cinemas

from flask_login import login_required, current_user
from pkg_init import db
from controllers.admin_ctl import admin_required
from models.sessions import Session
from models.seats import Seat, SeatSchema



app_seat = Blueprint("seats", __name__)
'''
views: in-use
'''
def get_seats():
    stmt=db.select(Seat)
    seats=db.session.scalars(stmt)
    totalseats = SeatSchema(many=True,).dump(seats)
    return totalseats

def get_seat_numbers():
    seats = get_seats()
    totalseatnumbers=[]
    totalseatnumbers.append('')
    for i in seats:
        totalseatnumbers.append(i['seat_number'])
    return sorted(list( dict.fromkeys(totalseatnumbers) ))

@app_seat.route("/seats_add",methods=( 'POST',) )
def add_seat():
    cinema_id = request.form['cinema_id']
    seat_number = request.form['seat_number']
    new_seat = Seat(
        seat_number=seat_number,
        cinema_id = cinema_id
    )
    db.session.add(new_seat)
    db.session.commit()
    return redirect(url_for('seats.create_total_seat',))

@app_seat.route("/seats/filte",methods=( 'POST',) )
@login_required
def filter_seat():
    cinemas = get_cinemas()
    cinemas.insert(0, '')
    seatnumbers = get_seat_numbers()
    totalseats = get_seats()

    cinema_id = request.form['cinema_id']
    seat_number = request.form['seat_number']
    if seat_number == ''and cinema_id !='' :
        stmt=db.select(Seat).filter_by(cinema_id=cinema_id)
        session=db.session.scalars(stmt)
        seats =  SeatSchema(many=True).dump(session)
        return render_template('cinema/seats.html', seats=seats,seatnumbers= seatnumbers, cinemas=cinemas)
    if cinema_id == '' and seat_number !='':
        stmt=db.select(Seat).filter_by(seat_number=seat_number)
        session=db.session.scalars(stmt)
        seats =  SeatSchema(many=True).dump(session)
        return render_template('cinema/seats.html', seats=seats,seatnumbers= seatnumbers, cinemas=cinemas)
    if cinema_id == '' and seat_number=='':
        return render_template('cinema/seats.html', seats=totalseats,seatnumbers= seatnumbers, cinemas=cinemas)
    stmt=db.select(Seat).filter_by(cinema_id=cinema_id, seat_number=seat_number)
    session=db.session.scalars(stmt)
    seats =  SeatSchema(many=True).dump(session)
    return render_template('cinema/seats.html', seats=seats,seatnumbers= seatnumbers, cinemas=cinemas,user=current_user.username)

@app_seat.route("/seats",  methods=('GET', 'POST'))
@login_required
def create_total_seat():
    cinemas = get_cinemas()
    cinemas.insert(0, '')

    totalseats = get_seats()
    seatnumbers = get_seat_numbers()
    return render_template('cinema/seats.html',user=current_user.username, seats=totalseats,seatnumbers= seatnumbers, cinemas=cinemas)

@app_seat.route("/ajax_seats/<int:a>", methods=['GET'])
def get_all_seats_by_cinema(a):
    stmt=db.select(Seat).filter_by(cinema_id=a)
    session=db.session.scalars(stmt)
    seats =  SeatSchema(many=True).dump(session)
    return seats

@app_seat.route("/seats/destribute_movie",methods=('GET','POST'))
@login_required
def add_playing_movie():
    cinemas = get_cinemas()
    totalseats = get_all_seats_by_cinema(cinemas[0]['id'])

    if request.method == 'POST':
        cinema_id = request.form['cinema_id']
        seat_id = request.form['seat_id']
        movie_id=request.form['movie_id']
        # add movie_id for seat room in cinema_id
        # alter table 'movies' insert seat_id =seat_id where movie_id=movie_id, cinema_id=cinema_id
        movie_check=Movie_Seat.query.filter_by(cinema_id=cinema_id, seat_id=seat_id,movie_id=movie_id).first()
        if movie_check:
            flash('movie already exist!')
        new_movie_seat = Movie_Seat(
            movie_id = movie_id,
            seat_id=seat_id,
            cinema_id = cinema_id
        )
        db.session.add(new_movie_seat)
        db.session.commit()
        return redirect(url_for('seats.add_playing_movie'))
    
    return render_template('cinema/seat_addmovie.html',cinemas=cinemas, seats= totalseats, user=current_user.username)

@app_seat.route("/cinemas/<int:cinema_id>/seats/<int:id>/delete",methods=('GET','POST'))
@login_required
def delete_a_seat(cinema_id,id):
    if request.method == 'POST':
        seat_check=Seat.query.filter_by(id=id,cinema_id=cinema_id).first()
        db.session.delete(seat_check)
        db.session.commit()
        return redirect(url_for('seats.create_total_seat'))
    return render_template('cinema/update_seat.html', user=current_user.username)

templates/cinema/all_cinames.html
{% extends 'cinema/index.html' %}

{% block info %}
<div class="py-2 mb-2" style="background-color: rgb(206, 208, 210);">
    Cinemas
</div>
<!-- cinemas -->

<div class="d-flex flex-column  ">
    <!--cinema modal toggle-->
    <button class="w-25 rounded mt-2" data-bs-toggle="modal" data-bs-target="#cinemaModal">
        <i class="bi bi-file-earmark-plus">
            Add cinema
        </i></button>
    <div class="row">

        {% for post in posts %}
        <div class="col-3">

            <button class="btn btn-outline-secondary my-2"
                    id="cinema_name">{{ post['cinema_name'] }}</button>
        </div>
        {% endfor %}
    </div>
</div>
<!-- cinemaModal -->
<div class="modal fade" id="cinemaModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Movie</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" class="w-50">
                    <div class="form-group">
                        <label for="cinema_name">cinema_name</label>
                        <input type="cinema_name" class="form-control my-3" name="cinema_name" id="cinema_name"
                            required>
                    </div>
                    <input type="submit" value="Add" class="btn btn-primary ">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}

templates/cinema/all_users.html
{% extends 'cinema/index.html' %}

{% block info %}

<div class="py-2 mb-2" style="background-color: rgb(206, 208, 210);">
    Users
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">name</th>
            <th scope="col">email</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <th scope="row">{{ user['id'] }}</th>
            <td>{{ user['username'] }}</td>
            <td>{{ user['email'] }}</td>
          </tr>
          {% endfor %}
    </tbody>
</table>



{% endblock %}

templates/cinema/index.html
{% extends 'base.html' %}


{% block content %}
<div class="row bg-light" style="height: 100vh">
    <div class="col-2 bg-secondary ">
        <div class="nav-l d-flex flex-column" style="font-size:25px;">
            <a style="color: white;" href="{{ url_for('cinema.get_cinema') }}">
                cinemas
            </a>
            <a style="color: white;" href="{{ url_for('movie.all_movies') }}">
                movies
            </a>
            <a style="color: white;" href="{{ url_for('seats.create_total_seat') }}">Seats</a>
            <a style="color: white;" href="{{ url_for('schedules.get_schedules') }}">Schedules</a>

            <a style="color: white;" href="{{ url_for('sessions.get_sessions') }}">
                Sessions</a>
            <a style="color: white;" href="{{ url_for('admin.get_users') }}">Users</a>
            <a style="color: white;" href="{{ url_for('orders.get_orders') }}">
                orders
            </a>

        </div>
    </div>


    <div class="col-10">
        {% block info %}{% endblock %}
    </div>


</div>

{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('.nav-l a').hover(function () {
            $('a').removeClass('active');
            $(this).addClass('active');
        })
    });
</script>
{% endblock %}

templates/cinema/main.html
{% extends 'cinema/index.html' %}

{% block info %}
<div class="d-flex justify-content-between p-2">

    <h1>ALL MOVIES</h1>
    <button class="rounded" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="bi bi-file-earmark-plus">Add
            new movie</i></button>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Movie</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" class="w-50">
                    <div class="form-group">
                        <label for="movie_name">movie_name</label>
                        <input type="movie_name" class="form-control my-3" name="movie_name" id="movie_name" required>
                    </div>
                    <div class="form-group">
                        <label for="movie_poster">movie poster link</label>
                        <input type="movie_poster" class="form-control my-3" name="movie_poster" id="movie_poster" required>
                    </div>
                    <div class="form-group">
                        <label for="introduction">introduction</label>
                        <textarea type="introduction" class="form-control my-3" name="introduction" id="introduction"
                            required></textarea>
                    </div>
                    
                    <div class=" mt-3">

                        <input type="submit" value="Add" class="btn btn-primary">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



{% for movie in posts %}


<div class="d-flex justify-content-between align-items-center bg-secondary my-1">
    <div class="d-flex flex-column">

        <label style="font-size: 20px; color: white;">{{ movie['movie_name'] }}</label>
        <label style="font-size: 16px; color: lightgray;">{{ movie['introduction'][0:100] }}...</label>
    </div>
    <div class="d-flex align-items-center " style="font-size: 1rem;color: white;">

        <button type="button" data-toggle="collapse" data-target={{"#collapseExample"+movie['id']|string}}
            aria-expanded="false" aria-controls="collapseExample">
            ^ schedule collapse
        </button>

        <a href="{{ url_for('movie.update_movie',movie_id=movie['id'], ) }}"><button
                class="mx-2"><i class="bi bi-pencil-square">Update</i></button></a>
        <!-- <button data-id={{movie['id']}} class="mx-2" id="deletemoview"><i class="bi bi-dash-circle ">Delete</i></button> -->
    </div>
    
</div>
<div class="collapse" id={{"collapseExample"+movie['id']|string}}>

    <div class="bg-light ">
        <div style="background-color: rgb(206, 208, 210);">
            Schedules
        </div>
        {% for schedule in movie['schedules'] %}
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">{{ schedule['schedule_date'].split(' ')[0] }}</th>
                    {% for session in schedule['sessions'] %}
                    <td>{{session['session_time'] }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>

        {% endfor %}
    </div>

</div>
{% endfor %}

{% endblock %}

{% block javascript %}
<script type="text/javascript">

</script>
{% endblock %}

templates/cinema/seats.html
{% extends 'cinema/index.html' %}

{% block info %}

<form method="post" class=" w-75" action="{{url_for('seats.add_seat')}}">
    <div class="form-group">
        <div class="form-group">
            <label for="seat_number">seat_number</label>
            <input type="number" class="form-control my-3" name="seat_number" id="seat_number" required>
        </div>
        <div class="form-group">
            <label for="cinemas">Choose a cinema:</label>
            <select name="cinema_id" id="cinema_name">
                {% for cinema in cinemas %}
                <option value="{{ cinema['id'] }}">{{ cinema['cinema_name'] }}</option>
                {% endfor %}
            </select>
        </div>
        <input type="submit" value="Add room seats capacity" class="btn btn-primary ">
        <input class="btn btn-secondary" type="submit" name="add_new_room" value="Save">
    </div>
</form>
<div class="d-flex">
    <button><a href="{{ url_for('seats.create_total_seat')}}">All</a></button>
    <form method="post" class="text-end me-4 w-75" action="{{url_for('seats.filter_seat')}}">
        <label for="seats">seat capacity</label>
        <select name="seat_number" id="seat_number">
            {% for seat in seatnumbers %}
                    <option value="{{ seat }}">{{ seat }}</option>
                    {% endfor %}
        </select>
        <label for="cinemas">cinema name</label>
        <select name="cinema_id" id="cinema_name">
            {% for cinema in cinemas %}
                    <option value="{{ cinema['id'] }}">{{ cinema['cinema_name'] }}</option>
                    {% endfor %}
        </select>
        <input class="btn btn-secondary" type="submit" name="filter" value="Filte">
    </form>
    <button><a href="{{ url_for('seats.add_playing_movie')}}"> Distribute movies</a></button>

</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">seat_number</th>
            <th scope="col">cinema_id</th>
            <th scope="col">operation</th>
        </tr>
    </thead>
    <tbody>
        {% for seat in seats %}
        <tr>
            <th scope="row">{{ seat['id'] }}</th>
            <td>{{ seat['seat_number'] }}</td>
            <td>{{ seat['cinema_id'] }}</td>
            <td><a href="{{ url_for('seats.delete_a_seat',id=seat['id'],cinema_id=seat['cinema_id'] ) }}">delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/cinema/update.html
{% extends 'cinema/index.html' %}

{% block info %}
<a href="{{ url_for('movie.all_movies')  }}"><button>
    < movies</button></a>

<form method="post" class=" w-75">
  <div class="form-group">

    <label for="movie_name">movie name</label>
    <input name="movie_name" id="movie_name" class="form-control my-3"
      value="{{ request.form['movie_name'] or post['movie_name'] }}" required>
  </div>
  <div class="form-group">

    <label for="movie_poster">movie poster</label>
    <input name="movie_poster" id="movie_poster" class="form-control my-3"
      value="{{ request.form['movie_poster'] or post['movie_poster'] }}" required>
  </div>
  <div class="form-group">
    <label for="introduction">introduction</label>
    <textarea name="introduction" class="form-control my-3"
      id="introduction">{{ request.form['introduction'] or post['introduction'] }}</textarea>
  </div>
  
  <input class="btn btn-secondary" type="submit" value="Save">
</form>
<hr>
<form action="{{ url_for('movie.delete_movie', movie_id=post['id']) }}" method="post">
  <input class="btn btn-danger" type="submit" value="Delete Movie" onclick="return confirm('Are you sure?');">
</form>
{% endblock %}

templates/cinema/update_seat.html
{% extends 'cinema/index.html' %}

{% block info %}
<form action="{{ url_for('seats.delete_a_seat', cinema_id=request.path.split('/')[2], id=request.path.split('/')[4]) }}"
    method="post">
    <input class="btn btn-danger" type="submit" value="Delete Seat" onclick="return confirm('Are you sure?');">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</form>
{% endblock %}