controllers/admin_ctl.py
from datetime import timedelta
import os
from flask import Blueprint, abort, flash, make_response, redirect, render_template, request, jsonify,session, url_for
from pkg_init import db, bcrypt
import jwt
from flask_jwt_extended import create_access_token, get_jwt_identity, jwt_required,create_refresh_token , set_access_cookies, set_refresh_cookies
from models.admin import Admin, AdminSchema
from models.users import User, UserSchema
from models.orders import Order, OrderSchema
from flask_login import login_user,login_required,current_user, logout_user

app_admin=Blueprint("admin",__name__)

# admin login function check
def admin_required():
    user_id = get_jwt_identity()
    stmt = db.select(Admin).filter_by(id=user_id)
    user=db.session.scalar(stmt)
    if not (user and user.admin):
        abort(401)
    else:
        return user
    
# admin login
@app_admin.route("/admin",methods=('GET', 'POST'))
def admin_login():
    # user_token = session.get('user_token')
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user =Admin.query.filter_by(email=username).first()
        # print('user', user, user.email)
        if user is None:
            error = 'Incorrect username.'
        elif not bcrypt.check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            # session.clear()
            expire=timedelta(days=1)
            access_token=create_access_token(identity=user.id,expires_delta=expire)
            refresh_token = create_refresh_token(identity=user.id,expires_delta=expire)
            # session['user_token'] = access_token
            login_user(user, remember=True)
            return redirect(url_for('cinema.get_cinema'))
            # resp = make_response(redirect(url_for('cinema.get_cinema')))
            # resp.set_cookie('resp', access_token)
            # # set_refresh_cookies(resp, refresh_token)
            # return resp

        flash(error)
    return render_template('auth/login.html')
    
    '''
    # retrieve input data
    user_info=AdminSchema().load(request.form)
    user=Admin.query.filter_by(email=user_info['email']).first()
    # error if admin not exist
    if not user :
        return {"error":"user not exist"},404
    # error if password incorrect
    elif not bcrypt.check_password_hash(user.password,user_info['password']):
        return {"error":"Incorrect username and password"}, 402
    # generate token for further use
    expire=timedelta(days=1)
    access_token=create_access_token(identity=user.id,expires_delta=expire)
    # return data for further use
    return {"user":user.username,"id":user.id, "token":access_token}
    
    '''


@app_admin.route('/logout')
@login_required
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('admin.admin_login'))        





# update user info
@app_admin.route("/admin",methods=['PUT'])
@jwt_required()
def update_user():
    # check admin login
    admin=admin_required()
    # get use input
    user_info= AdminSchema().load(request.form)
    # update user information
    admin.username= user_info.get("username", admin.username)
    if user_info.get("password", admin.password) != admin.password:
        admin.password=bcrypt.generate_password_hash(user_info.get("password", admin.password)).decode('utf-8')
    admin.email=user_info.get("email", admin.email)
    db.session.commit()
    return AdminSchema().dump(admin), 201

# retrieve all customers' data 
@app_admin.route("/admin/users",methods=['GET'])
@login_required
def get_users():
    # admin=admin_required()
    users = User.query.all()
    res=UserSchema(many=True,exclude=['password','comments','votes']).dump(users)
    # return jsonify(res)
    return render_template('cinema/all_users.html', users=res,user=current_user.username)

templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<!-- Bootstrap CSS -->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<body>
    <nav class="navbar bg-dark px-5 text-white">
        <h1 ><a  style="text-decoration: none; color: white;" href="{{ url_for('index_page') }}">Flaskr</a></h1>
        <ul class="nav " style="width: 130px;">
            {% if user %}
            <li style="margin-right: 10px;">{{ user }}</li>
            <li><a class="pl-3" style="display: block;" href="{{ url_for('admin.logout') }}">Log Out</a></li>
            {% else %}
            <li><a class="text-white" href="{{ url_for('admin.admin_login') }}">Log In</a></li>
            {% endif %}
        </ul>
    </nav>


    {% for message in get_flashed_messages() %}
    <div class="alert alert-primary">{{ message }}</div>
    {% endfor %}

    {% block content %}{% endblock %}

    <!-- Bootstrap Javascripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
    {% block javascript %}{% endblock %}
</body>